name: autoarr-landing-page
runtime:
  name: nodejs
  options:
    typescript: true
description: AutoArr landing page infrastructure - Cloudflare Pages + Firebase
config:
  pulumi:tags:
    value:
      pulumi:template: typescript
